export const stories = [
  {
    id: 1,
    name: 'Avatar1 av',
    img: require('./public/assets/avatar1.jpg'),
  },
  {
    id: 2,
    name: 'Avatar2 av',
    img: require('./public/assets/avatar2.jpg'),
  },
  {
    id: 3,
    name: 'Avatar3 av',
    img: require('./public/assets/avatar3.jpg'),
  },
  {
    id: 4,
    name: 'Avatar4 av',
    img: require('./public/assets/avatar4.png'),
  },

  {
    id: 5,
    name: 'Avatar5 av',
    img: require('./public/assets/avatar5.jpg'),
  },
  {
    id: 6,
    name: 'Avatar6 av',
    img: require('./public/assets/avatar6.png'),
  },
  {
    id: 7,
    name: 'Avatar7 av',
    img: require('./public/assets/avatar7.png'),
  },
  {
    id: 8,
    name: 'Avatar8 av',
    img: require('./public/assets/te1.png'),
  },
  {
    id: 9,
    name: 'Avatar9 av',
    img: require('./public/assets/te2.png'),
  },
  {
    id: 10,
    name: 'Avatar10 av',
    img: require('./public/assets/te3.png'),
  },
];

export const posts = [
  {
    id: 1,
    creator: 'Avatar1',
    postImg: require('./public/assets/post4.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 2,
    creator: 'Avatar2',
    postImg: require('./public/assets/post1.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 3,
    creator: 'Avatar3',
    postImg: require('./public/assets/post3.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 4,
    creator: 'Avatar4',
    postImg: require('./public/assets/post5.jpeg'),
    likes: '42,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 5,
    creator: 'Avatar2',
    postImg: require('./public/assets/post2.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 6,
    creator: 'Avatar1',
    postImg: require('./public/assets/post6.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 7,
    creator: 'Avatar2',
    postImg: require('./public/assets/post7.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 8,
    creator: 'Avatar3',
    postImg: require('./public/assets/post8.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 9,
    creator: 'Avatar4',
    postImg: require('./public/assets/post9.jpeg'),
    likes: '42,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 10,
    creator: 'Avatar2',
    postImg: require('./public/assets/post10.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 11,
    creator: 'Avatar1',
    postImg: require('./public/assets/post11.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 12,
    creator: 'Avatar2',
    postImg: require('./public/assets/post12.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 13,
    creator: 'Avatar3',
    postImg: require('./public/assets/post3.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 14,
    creator: 'Avatar4',
    postImg: require('./public/assets/post5.jpeg'),
    likes: '42,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 15,
    creator: 'Avatar2',
    postImg: require('./public/assets/post2.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 16,
    creator: 'Avatar1',
    postImg: require('./public/assets/post4.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 17,
    creator: 'Avatar2',
    postImg: require('./public/assets/post1.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 18,
    creator: 'Avatar3',
    postImg: require('./public/assets/post3.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 19,
    creator: 'Avatar4',
    postImg: require('./public/assets/post5.jpeg'),
    likes: '42,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 20,
    creator: 'Avatar2',
    postImg: require('./public/assets/post2.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 21,
    creator: 'Avatar1',
    postImg: require('./public/assets/post4.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 22,
    creator: 'Avatar2',
    postImg: require('./public/assets/post1.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 23,
    creator: 'Avatar3',
    postImg: require('./public/assets/post3.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 24,
    creator: 'Avatar4',
    postImg: require('./public/assets/post5.jpeg'),
    likes: '42,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 25,
    creator: 'Avatar2',
    postImg: require('./public/assets/post2.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 26,
    creator: 'Avatar1',
    postImg: require('./public/assets/post4.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 27,
    creator: 'Avatar2',
    postImg: require('./public/assets/post1.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 28,
    creator: 'Avatar3',
    postImg: require('./public/assets/post3.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 29,
    creator: 'Avatar4',
    postImg: require('./public/assets/post5.jpeg'),
    likes: '42,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 30,
    creator: 'Avatar2',
    postImg: require('./public/assets/post2.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 31,
    creator: 'Avatar1',
    postImg: require('./public/assets/post4.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 32,
    creator: 'Avatar2',
    postImg: require('./public/assets/post1.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 33,
    creator: 'Avatar3',
    postImg: require('./public/assets/post3.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 34,
    creator: 'Avatar4',
    postImg: require('./public/assets/post5.jpeg'),
    likes: '42,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 35,
    creator: 'Avatar2',
    postImg: require('./public/assets/post2.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 36,
    creator: 'Avatar1',
    postImg: require('./public/assets/post4.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 37,
    creator: 'Avatar2',
    postImg: require('./public/assets/post1.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 38,
    creator: 'Avatar3',
    postImg: require('./public/assets/post3.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 39,
    creator: 'Avatar4',
    postImg: require('./public/assets/post5.jpeg'),
    likes: '42,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    id: 40,
    creator: 'Avatar2',
    postImg: require('./public/assets/post2.jpeg'),
    likes: '12,278',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
];
